//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefreshDB.Database.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instance
    {
        public int id { get; set; }
        public string name { get; set; }
        public string servername { get; set; }
        public string SQLUsername { get; set; }
        public string SQLPassword { get; set; }
        public int environment_id { get; set; }
    }
}
